spring:
  application:
      name: activity-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_NAME}

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}


server:
  port: 8082



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking



#monogoDB
