spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}




  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    database: POSTGRESQL


server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


